portList = []
print(f"[+]portList starts as an empty list")
print(f"portList = {portList}")
print("[+]use the list append method (.append()) to add port 21")
portList.append(21)
print(f"portList = {portList}")
portList.append(80)
print("[+]use the list append method to add port 80")
print(f"portList = {portList}")
portList.append(443)
print("[+]use the list append method to add port 443")
print(f"portList = {portList}")
portList.append(25)
print("[+]use the list append method to add port 25")
print(f"portList = {portList}")
print("[+]use the sort method to sort the list")
portList.sort()
print(f"portList = {portList}")
pos = portList.index(80)
print("[+]use the index method to find the index position of port 80, then show how many ports there are before port 80")
# this works because the of zero index. Even though 80 is the 3rd number in the list, it is at index 2 (0,1,2). If indexes began at 1, we would have to do "there are {pos -1}" instead.
print(f"There are {pos} port to scan before 80.")
print("[+]Use the remove method to remove port 443 from the list")
portList.remove(443)
print(f"portList = {portList}")
cnt = len(portList)
print("Use the len function on portlist to show how many elements are in portList")
print(f"[+]Scanning {cnt} total ports.")

